version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    #network_mode: host
  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./docker/grafana.env
    #network_mode: host
    ports:
      - "3000:3000"
